version: "3"
services:
  kaggle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaggle
    volumes:
      - ./src:/app/src
      # X11 ソケットの共有は試してみる価値はありますが、Mac では必須ではない場合もあります
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=host.docker.internal:0
    tty: true
    stdin_open: true
    command: ["bash"]
