
services:
  ollama:
    image: ollama/ollama:0.9.2
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      # 公式推奨の接続文字列
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=False       # シングルユーザーモード
    depends_on:
      - ollama
    restart: unless-stopped
    volumes:
      - openwebui_data:/app/backend/data

volumes:
  ollama_data:
  openwebui_data:
